"""empty message

Revision ID: 30af5d74acf5
Revises: dfb1e75df0f0
Create Date: 2025-05-14 20:33:20.557827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30af5d74acf5'
down_revision = 'dfb1e75df0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
