"""empty message

Revision ID: b67810764712
Revises: a7dad796b1ab
Create Date: 2025-05-16 20:53:44.058037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67810764712'
down_revision = 'a7dad796b1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rescuer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['rescuer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rescuer_id')

    # ### end Alembic commands ###
