"""empty message

Revision ID: fcd73bdfe740
Revises: 30af5d74acf5
Create Date: 2025-05-15 19:16:07.013985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd73bdfe740'
down_revision = '30af5d74acf5'
branch_labels = None
depends_on = None

user_role_enum = sa.Enum('ADMIN', 'ADOPTER', 'RESCUER', name='userrole')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind())
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('ADMIN', 'ADOPTER', 'RESCUER', name='userrole'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        
    user_role_enum.drop(op.get_bind())

    # ### end Alembic commands ###
